export const CardImages = {
  "100CHip": "https://upload.wikimedia.org/wikipedia/commons/f/fa/%24100_chip.svg",
  "25CHip": "https://upload.wikimedia.org/wikipedia/commons/5/5a/%2425_chip.svg",
  "5CHip": "https://upload.wikimedia.org/wikipedia/commons/f/f6/%245_chip.svg",
  "1Chop": "https://upload.wikimedia.org/wikipedia/commons/e/ea/%241_chip_alternate.svg",
  Back: "https://upload.wikimedia.org/wikipedia/commons/8/87/Card_back_05.svg",
  Back2:
    "https://upload.wikimedia.org/wikipedia/commons/d/d8/Atlas_deck_card_back_blue_and_brown.svg",
  Back3:
    "https://upload.wikimedia.org/wikipedia/commons/7/7d/Atlas_deck_card_back_green_and_dark_red.svg",
  Back4:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Card_back_03c.svg/640px-Card_back_03c.svg.png",
  Back5:
    "https://upload.wikimedia.org/wikipedia/commons/3/3f/Card_back_03b.svg",
  Back6:
    "https://upload.wikimedia.org/wikipedia/commons/3/30/Card_back_05a.svg",
  Back7: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Card_back_01.svg",
  Back8: "https://upload.wikimedia.org/wikipedia/commons/8/80/Jeu_d%27Aluette_-_Grimaud_-_1860_-_Back_side.jpg",
  "1C": "https://upload.wikimedia.org/wikipedia/commons/e/eb/AC.svg",
  "1D": "https://upload.wikimedia.org/wikipedia/commons/6/6d/AD.svg",
  "1S": "https://upload.wikimedia.org/wikipedia/commons/2/27/AS.svg",
  "1H": "https://upload.wikimedia.org/wikipedia/commons/8/87/AH.svg",
  "2C": "https://upload.wikimedia.org/wikipedia/commons/6/69/2C.svg",
  "2D": "https://upload.wikimedia.org/wikipedia/commons/f/fb/2D.svg",
  "2H": "https://upload.wikimedia.org/wikipedia/commons/9/9d/2H.svg",
  "2S": "https://upload.wikimedia.org/wikipedia/commons/d/de/2S.svg",
  "3C": "https://upload.wikimedia.org/wikipedia/commons/7/70/3C.svg",
  "3D": "https://upload.wikimedia.org/wikipedia/commons/5/57/3D.svg",
  "3H": "https://upload.wikimedia.org/wikipedia/commons/3/3a/3H.svg",
  "3S": "https://upload.wikimedia.org/wikipedia/commons/c/ce/3S.svg",
  "4C": "https://upload.wikimedia.org/wikipedia/commons/2/25/4C.svg",
  "4D": "https://upload.wikimedia.org/wikipedia/commons/c/c7/4D.svg",
  "4H": "https://upload.wikimedia.org/wikipedia/commons/6/6f/4H.svg",
  "4S": "https://upload.wikimedia.org/wikipedia/commons/c/cc/4S.svg",
  "5C": "https://upload.wikimedia.org/wikipedia/commons/6/6d/5C.svg",
  "5D": "https://upload.wikimedia.org/wikipedia/commons/d/d9/5D.svg",
  "5H": "https://upload.wikimedia.org/wikipedia/commons/0/03/5H.svg",
  "5S": "https://upload.wikimedia.org/wikipedia/commons/a/ac/5S.svg",
  "6C": "https://upload.wikimedia.org/wikipedia/commons/6/62/6C.svg",
  "6D": "https://upload.wikimedia.org/wikipedia/commons/c/cf/6D.svg",
  "6H": "https://upload.wikimedia.org/wikipedia/commons/a/a2/6H.svg",
  "6S": "https://upload.wikimedia.org/wikipedia/commons/1/1f/6S.svg",
  "7C": "https://upload.wikimedia.org/wikipedia/commons/6/68/7C.svg",
  "7D": "https://upload.wikimedia.org/wikipedia/commons/5/5a/7D.svg",
  "7H": "https://upload.wikimedia.org/wikipedia/commons/e/e1/7H.svg",
  "7S": "https://upload.wikimedia.org/wikipedia/commons/a/a1/7S.svg",
  "8C": "https://upload.wikimedia.org/wikipedia/commons/9/94/8C.svg",
  "8D": "https://upload.wikimedia.org/wikipedia/commons/8/80/8D.svg",
  "8H": "https://upload.wikimedia.org/wikipedia/commons/3/34/8H.svg",
  "8S": "https://upload.wikimedia.org/wikipedia/commons/3/36/8S.svg",
  "9C": "https://upload.wikimedia.org/wikipedia/commons/6/63/9C.svg",
  "9D": "https://upload.wikimedia.org/wikipedia/commons/0/09/9D.svg",
  "9H": "https://upload.wikimedia.org/wikipedia/commons/e/e0/9H.svg",
  "9S": "https://upload.wikimedia.org/wikipedia/commons/3/31/9S.svg",
  "10C": "https://upload.wikimedia.org/wikipedia/commons/c/c7/10C.svg",
  "10D": "https://upload.wikimedia.org/wikipedia/commons/8/83/10D.svg",
  "10H": "https://upload.wikimedia.org/wikipedia/commons/8/8a/10H.svg",
  "10S": "https://upload.wikimedia.org/wikipedia/commons/1/16/10S.svg",
  "11C": "https://upload.wikimedia.org/wikipedia/commons/1/11/JC.svg",
  "11D": "https://upload.wikimedia.org/wikipedia/commons/3/33/JD.svg",
  "11H": "https://upload.wikimedia.org/wikipedia/commons/1/15/JH.svg",
  "11S": "https://upload.wikimedia.org/wikipedia/commons/d/d9/JS.svg",
  "12C": "https://upload.wikimedia.org/wikipedia/commons/9/9e/QC.svg",
  "12D": "https://upload.wikimedia.org/wikipedia/commons/6/63/QD.svg",
  "12H": "https://upload.wikimedia.org/wikipedia/commons/d/d2/QH.svg",
  "12S": "https://upload.wikimedia.org/wikipedia/commons/3/35/QS.svg",
  "13C": "https://upload.wikimedia.org/wikipedia/commons/e/e1/KC.svg",
  "13D": "https://upload.wikimedia.org/wikipedia/commons/0/06/KD.svg",
  "13H": "https://upload.wikimedia.org/wikipedia/commons/e/e5/KH.svg",
  "13S": "https://upload.wikimedia.org/wikipedia/commons/5/5c/KS.svg",
};
