import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Deck from "../components/deck";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Poker Client</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen flex flex-col items-center p-4 bg-gradient-to-br from-blue-400  to-violet-900">
        <h1 className="text-4xl font-bold text-white">Poker Client</h1>
        <Image src="https://upload.wikimedia.org/wikipedia/commons/c/c0/Texas_Hold%27em_Poker_Table_with_Blinds.svg" width={500} height={500} alt="Texas Hold'em Poker Table" />
        <Deck />
      </div>
    </>
  );
};

export default Home;
