import ProfileBasic from "../components/profileBasic";
import Head from "next/head";

const Profile = () => {
  return (
    <>
      <Head>
        <title>Poker Client</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen flex flex-col justify-center items-center p-4 bg-gradient-to-br from-blue-400  to-violet-900">
        <ProfileBasic />
      </div>
    </>
  );
};

export default Profile;
