import ProfileBasic from "../components/profileBasic";
import Head from "next/head";
import { useEffect, useState } from "react";
import { IUser } from "../contexts/userContexts";
import { getCookie } from "typescript-cookie";
import { TokenValidator } from "../components/LandingPage";

const Profile = () => {
  const [user, setUser] = useState<IUser>();
  useEffect(() => {
    if (getCookie("user") !== undefined) {
      setUser(JSON.parse(getCookie("user")!));
    }
  }, []);
  let isValid = TokenValidator(user?.access_token!)
  if (isValid && user) {
    return (
      <>
        <Head>
          <title>Poker Client</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="w-screen h-screen flex flex-col justify-center items-center p-4 bg-gradient-to-br from-blue-400  to-violet-900">
          <ProfileBasic user={user}  />
        </div>
      </>
    );
  }
 
};

export default Profile;
